### ISSUE TITLE
Gráficas acumuladas de vacunas caen a cero

### ISSUE THREAD

**Issue by Johnbo** [Pakillo/COVID19-Andalucia#14]
La serie _dosis entregadas_ de la primera gráfica de vacunas y la serie _porcentaje de población vacunada_ de la segunda tienen una repentina bajada al valor 0 para la fecha más reciente.

**Comment by Pakillo** [comment]
Gracias @Johnbo . Lo vi anoche. Surgió un problema con el dataset de origen en Datadista (https://github.com/datadista/datasets/issues/122). Ya está resuelto y actualizadas las gráficas.
¡Gracias por el aviso!
