### ISSUE TITLE
Visualización dinámica de Tendencias en Incidencia Acumulada por Municipio

### ISSUE THREAD

**Issue by dgrcode** [Pakillo/COVID19-Andalucia#15]
Lo primero, quería agradecerte que hayas creado y mantengas esta web. Es muy útil para entender la situación actual de la pandemia en Andalucía, y entro prácticamente a diario desde que la encontré, hace ya más de un año.

Una de las cosas que me gustaría poder ver en la página es una versión dinámica del gráfico de "Tendencias en Incidencia Acumulada por Municipio". Me refiero a este:
<img width=400 src="https://user-images.githubusercontent.com/17493200/125602865-6067bb09-3945-4902-b825-a56e3eeaa8a9.png"/>

Con versión dinámica me refiero a poder ver la secuencia de varios días consecutivos y ver cómo se mueven los puntos. La foto estática (que hay ahora) es útil, pero ver el movimiento de los puntos a lo largo del tiempo creo que daría mucha más información. No es lo mismo estar en 800 de IA a 14 días viniendo de 1200 que viniendo de 300.

Sería equivalente a ver una foto fija de satélite o una secuencia:
![radar aemet](https://user-images.githubusercontent.com/17493200/125608155-2e02b97b-da0f-4eac-926e-2f0d8a3ea69a.gif)

También se vería muy bien la tendencia generalizada en Andalucía como conjunto, observando cómo se mueve la nube de puntos. Por ejemplo, si en general la nube sube, es que la incidencia está subiendo.

Mirando el código un poco por encima, no he encontrado cómo se generan las gráficas, pero si puedo ayudar con algo estaré encantado de poder colaborar.

**Comment by Pakillo** [comment]
Hola Daniel,

Me alegro de que la web te sea útil desde hace tanto tiempo. Muchas veces he pensado en dejar de actualizarla (sobre todo cuando la Junta decide cambiar el formato de los datos que ofrece y tengo que volver a adaptar los scripts...). Pero por ahora parece que el COVID no se va, así que intentaré mantenerla actualizada, aunque no pueda dedicarle mucho tiempo libre a mejorarla.

Gracias por la sugerencia. He implementado algo parecido a lo que me pides (creo): https://pakillo.github.io/COVID19-Andalucia/evolucion-coronavirus-andalucia.html#datos-por-municipio. Usando plotly (https://plotly.com/r/). 

Por si te animas a mejorarla, el código que genera la figura está aquí: https://github.com/Pakillo/COVID19-Andalucia/blob/f58d6dcb327f39fd76a88ef45cac02939375bfa1/evolucion-coronavirus-andalucia.Rmd#L1472-L1506

Saludos

**Comment by dgrcode** [comment]
Buenas, acabo de verlo en vivo en la web, como cada lunes por la mañana jaja. Está increíble 👏 👏 👏  Se ve muy claro como la tendencia era bastante buena pero a partir de julio se descontrola. Me parece que se entiende muy bien. Muchas gracias por implementarlo!

Es la primera vez que me cruzo con código en R, pero voy a intentar echarlo a andar en local y ver si soy capaz de tocar cosas. Lo único que intentaría cambiar sería quitar el filtro `filter(IA.14d < 1000, IA.cambio < 200) %>%`, e intentar poner el zoom por defecto dentro de ese rango. De esa manera se podría hacer zoom hacia fuera para ver cómo se mueven los puntos que están por encima de 1000 de IA o 200% de cambio. Igual no aporta mucho, pero ya me lo voy a tomar como un reto para tocar código en R.

Me imagino que tiene que ser bastante duro y frustrante intentar automatizar algo que tenga que ver con nuestras administraciones públicas. No son demasiado amigos de la tecnología. Estaría bien que la junta tuviera un fondo para gente como tú haciendo estos proyectos. Tu web es literalmente mucho mejor que cualquier web oficial donde pongan datos del covid, que no me extrañaría que la hayan hecho en alguna consultoría por una cantidad vergonzosa de dinero.

Cierro el issue. Si consigo hacer los cambios abro un PR y comentamos ahí.

Muchas gracias! 🙌

**Comment by Johnbo** [comment]
Enhorabuena a ambos. El nuevo gráfico es muy clarificador acerca de las tendencias. Por otra parte, @Pakillo, te agradezco una vez más que mantengas la página, ya que no he encontrado ninguna otra que ofrezca tanta información y al mismo tiempo tan bien segmentada y _consumible_.

**Comment by Pakillo** [comment]
Hola,

Gracias a ambos por el ánimo y vuestras palabras. Lo dicho, mientras pueda sacar un ratito intentaré mantener la web.

He ampliado la figura (tanto la estática como la dinámica) para incluir cambios en la IA de hasta el 500%: https://pakillo.github.io/COVID19-Andalucia/evolucion-coronavirus-andalucia.html#datos-por-municipio. Creo que en efecto así se ven mejor las tendencias. ¡Gracias por la sugerencia!

Más allá de 500% creo que no merece la pena, porque hay algún municipio con subidas erráticas de hasta 5000% que provoca un apelotonamiento de puntos en la esquina inferior, sin que se pueda ver bien lo que pasa en el resto de municipios.
